FROM golang:1.16 as base

WORKDIR /go/src/github.com/percona/mongodb_exporter

COPY . .

RUN make build

FROM quay.io/sysdig/sysdig-mini-ubi:1

COPY --from=base /go/src/github.com/percona/mongodb_exporter/mongodb_exporter /bin/mongodb_exporter

EXPOSE      9216
USER        59000:59000

ENTRYPOINT [ "/bin/mongodb_exporter" ]